PPS-Client: client/pps-client.cpp File Reference
pps-client.cpp File Reference
This file contains the principal PPS-Client controller functions and structures.
#include "../client/pps-client.h"
Functions
int adjtimex (struct timex *timex)
class List rawErr (SLEW_LEN)
int initialize (bool verbose)
bool getAcquireState (void)
void setHardLimit (double avgCorrection)
void getTimeSlew (int rawError)
int clampJitter (int rawError)
void makeAverageIntegral (double avgCorrection)
bool integralIsReady (void)
double getMovingAverage (int timeCorrection)
int getNearestSecond (void)
void setClocktoNISTtime (void)
void setClockToGPStime (void)
void buildRawErrorDistrib (int rawError, double errorDistrib[], unsigned int *count)
void getAvgNoiseLevel (int rawError)
bool detectDelaySpike (int rawError)
int removeNoise (int rawError)
double getIntegral (void)
void savePPStime (int timeCorrection)
int signedFractionalSeconds (int fracSec)
void detectMissedPPS (void)
bool detectExteralSystemClockChange (struct timeval pps_t)
void setClockFractionalSecond (int correction)
int correctFractionalSecond (struct timeval *pps_t)
void doTimeFixups (struct timeval pps_t)
int makeTimeCorrection (struct timeval pps_t)
int checkPPSInterrupt (void)
struct timespec setSyncDelay (int timeAt, int fracSec)
int readPPS_SetTime (bool verbose, timeCheckParams *tcp, pps_handle_t *pps_handle, int *pps_mode)
void waitForPPS (bool verbose, pps_handle_t *pps_handle, int *pps_mode)
int main (int argc, char *argv[])
Variables
const char * version = "2.0.1"
Program v2.0.0 updated on 9 Jul 2020.
struct G g
Declares the global variables defined in pps-client.h.
struct ppsFiles f
PPS-Client internal files.
bool writeJitterDistrib
bool writeErrorDistrib
bool threadIsRunning = false
bool readState = false
Detailed Description
This file contains the principal PPS-Client controller functions and structures.
The PPS-Client daemon synchronizes the system clock to a Pulse-Per-Second (PPS) source to a resolution of one microsecond with an absolute accuracy of a few microseconds. To obtain this level of performance PPS-Client provides offset corrections every second and frequency corrections every minute. This and removal of jitter in the reported PPS time keeps the system clock continuously synchronized to the PPS source.
A wired GPIO connection is required from a PPS source. Synchronization is provided by the rising edge of that PPS source which is connected to GPIO 4 on Raspberry Pi.
The executable for this daemon is "/usr/sbin/pps-client"
The daemon script is "/lib/systemd/system/pps-client.service"
The configuration file is "/etc/pps-client.conf"
Definition in file pps-client.cpp.
Function Documentation
adjtimex()
int adjtimex (struct timex * timex)
System call
Referenced by initialize(), loadLastState(), makeTimeCorrection(), setClockFractionalSecond(), setClockToGPStime(), and setClocktoNISTtime().
buildRawErrorDistrib()
void buildRawErrorDistrib (int rawError, double errorDistrib[], unsigned int * count)
Constructs an exponentially decaying distribution of rawError with a half life on individual samples of 1 hour.
Parameters
[in] rawError The distribution values.
[out] errorDistrib The distribution being constructed.
[in,out] count The count of distribution samples.
Definition at line 492 of file pps-client.cpp.
References ERROR_DISTRIB_LEN, g, HARD_LIMIT_1, G::hardLimit, RAW_ERROR_DECAY, and RAW_ERROR_ZERO.
Referenced by removeNoise().
checkPPSInterrupt()
int checkPPSInterrupt (void)
Logs loss and resumption of the PPS interrupt. Can force exit if the interrupt is lost for more than one hour when "exit-lost-pps=enable" is set in the config file.
Returns
0 on success, else -1 on error.
Definition at line 1044 of file pps-client.cpp.
Referenced by waitForPPS().
clampJitter()
int clampJitter (int rawError)
Clamps rawError to an adaptive value relative to the average rawError and determined at the current G.hardLimit value from the current value of G.noiseLevel.
Once the rawError values have been limited to values of +/- 1 microsecond and the control loop has settled, this clamping causes the controller to make the average number of positive and negative rawError values equal rather than making the sum of the positive and negative jitter values zero. This removes the bias that would otherwise be introduced by the rawError values which are largely random and consequently would introduce a constantly changing random offset. The result is also to move the average PPS interrupt delay to its median value.
Parameters
[in] rawError The raw error value to be converted to a zero error.
Definition at line 248 of file pps-client.cpp.
References g, and G::hardLimit.
Referenced by removeNoise().
correctFractionalSecond()
int correctFractionalSecond (struct timeval * pps_t)
Removes the error potentially introduced in the interrupt time by an external clock change. The correction that is introduced only needs to be good enough that the time servo can track out any remaining error.
Parameters
[in] pps_t The delayed time of the PPS rising edge returned by the system clock.
Definition at line 873 of file pps-client.cpp.
References setClockFractionalSecond().
Referenced by doTimeFixups().
detectDelaySpike()
bool detectDelaySpike (int rawError)
Removes jitter delay spikes by returning "true" as long as the jitter value remains beyond a threshold that is determined by the curent value of G.noiseLevel.
Parameters
[in] rawError The raw error vlue to be tested for being a delay spike.
Returns
"true" if a delay spike is detected. Else "false".
Definition at line 544 of file pps-client.cpp.
References G::clampAbsolute, g, G::hardLimit, G::isControlling, and NOISE_LEVEL_MIN.
Referenced by removeNoise().
detectExteralSystemClockChange()
bool detectExteralSystemClockChange (struct timeval pps_t)
Determines whether the system clock has been set externally.
Parameters
[in] pps_t The delayed time of the PPS rising edge returned by the system clock.
Returns
true if clock was set else false.
Definition at line 766 of file pps-client.cpp.
References G::avgSlew, G::clockChanged, g, HARD_LIMIT_1, G::hardLimit, G::isControlling, G::seq_num, SLEW_LEN, SLEW_MAX, G::t_count, G::t_now, and writeToLog().
Referenced by doTimeFixups().
detectMissedPPS()
void detectMissedPPS (void)
Advances a monotonic time count G.t_count second by second. That happens even when this function is not called in a particular second.
The G.t_count value is used in detectExteralSystemClockChange() to determine if the system time has been set externally.
Definition at line 720 of file pps-client.cpp.
References g, getNearestSecond(), G::seq_num, G::t_count, G::t_mono_last, G::t_mono_now, G::t_now, and writeToLog().
Referenced by readPPS_SetTime().
doTimeFixups()
void doTimeFixups (struct timeval pps_t)
Makes any necessary corrections to the system time required or caused by external time keepers.
Parameters
[in] pps_t The delayed time of the PPS rising edge returned by the system clock.
Definition at line 903 of file pps-client.cpp.
References G::consensusTimeError, correctFractionalSecond(), detectExteralSystemClockChange(), G::doNISTsettime, G::doSerialsettime, g, getNearestSecond(), G::nistTimeUpdated, SECS_PER_MINUTE, G::serialTimeError, G::serialTimeUpdated, setClockToGPStime(), setClocktoNISTtime(), sysCommand(), G::t_count, and G::t_now.
Referenced by makeTimeCorrection().
getAcquireState()
bool getAcquireState (void)
Returns true when the control loop can begin to control the system clock frequency. At program start only the time slew is adjusted because the drift can be too large for it to be practical to adjust the system clock frequency to correct for it. SLEW_MAX sets a reasonable limit below which frequency offset can also be adjusted to correct system time.
Consequently, once the drift is within SLEW_MAX microseconds of zero and the controller has been running for at least 60 seconds (time selected for convenience), this function returns "true" causing the controller to begin to also adjust the system clock frequency offset.
Returns
"true" when the control loop can begin to control the system clock frequency. Else "false".
Definition at line 138 of file pps-client.cpp.
References G::avgSlew, g, SECS_PER_MINUTE, G::seq_num, SLEW_MAX, G::slewAccum_cnt, and G::slewIsLow.
Referenced by makeTimeCorrection().
getAvgNoiseLevel()
void getAvgNoiseLevel (int rawError)
Averages rawError (exponential average) and the positive half of the rawError distribution to determine an average noise level.
Parameters
[in] rawError The fractional second time of arrival of the PPS.
Definition at line 525 of file pps-client.cpp.
Referenced by removeNoise().
getIntegral()
double getIntegral (void)
if G.hardLimit == HARD_LIMIT_1, gets an integral time correction as a 10 second average of integrals of average time corrections over one minute. Otherwise gets the integral time correction as the single last integral of average time corrections over one minute.
Returns
The integral of time correction values.
Definition at line 648 of file pps-client.cpp.
References G::avgIntegral, g, HARD_LIMIT_1, G::hardLimit, G::integral, G::integralCount, NUM_INTEGRALS, and recordFrequencyVars().
Referenced by makeTimeCorrection().
getMovingAverage()
double getMovingAverage (int timeCorrection)
Maintains G.correctionFifo which contains second-by-second values of time corrections over the last minute, accumulates a rolling sum of these and returns the moving average correction over the last minute.
Although moving average is more complicated to generate than a conventional expponential average, moving averge has almost the same amount of noise reduction per sample but no history of noise disburbances that occurred in any previous minute. Consequently, the servo loop can converge significantly faster using a moving average.
Parameters
[in] timeCorrection The time correction value to be accumulated.
Returns
The average correction value.
Definition at line 365 of file pps-client.cpp.
References G::correctionAccum, G::correctionFifo, G::correctionFifo_idx, G::correctionFifoCount, g, PER_MINUTE, and SECS_PER_MINUTE.
Referenced by makeTimeCorrection().
getNearestSecond()
int getNearestSecond (void)
Returns the time of day as the nearest integer to the system time. Because detectMissedPPS() is called very near the rollover of the second, this prevents G.t_now from being initialized with the integer value of the previous second if detectMissedPPS() is called slightly ahead of rollover.
Definition at line 395 of file pps-client.cpp.
Referenced by detectMissedPPS(), doTimeFixups(), and waitForPPS().
getTimeSlew()
void getTimeSlew (int rawError)
Gets the average time offset from zero over the interval SLEW_LEN and updates avgSlew with this value every SLEW_LEN seconds. Excludes all large delay spikes from the average.
Parameters
[in] rawError The raw error to be accumulated to determine average slew including delay spikes.
Definition at line 204 of file pps-client.cpp.
References G::avgSlew, g, LARGE_SPIKE, rawErr(), SLEW_LEN, G::slewAccum, and G::slewAccum_cnt.
Referenced by removeNoise().
initialize()
int initialize (bool verbose)
Sets global variables to initial values at startup or restart and sets system clock frequency offset to zero.
Parameters
[in] verbose Enables printing of state status params when "true".
Definition at line 75 of file pps-client.cpp.
References adjtimex(), assignProcessorAffinity(), G::cpuVersion, g, getConfigs(), getRPiCPU(), HARD_LIMIT_NONE, G::hardLimit, INTEGRAL_GAIN, G::integralGain, INV_GAIN_0, G::invProportionalGain, G::isVerbose, G::nCores, G::t3, ZERO_OFFSET_RPI3, ZERO_OFFSET_RPI4, and G::zeroOffset.
Referenced by main(), and readPPS_SetTime().
integralIsReady()
bool integralIsReady (void)
Advances the G.correctionFifo index each second and returns "true" when 60 new time correction values have been accumulated in G.correctionAccum.
When a value of "true" is returned, new average time correction integrals have been generated by makeAverageIntegral() and are ready for use.
Returns
"true" when ready, else "false".
Definition at line 333 of file pps-client.cpp.
References G::correctionFifo_idx, g, and SECS_PER_MINUTE.
Referenced by makeTimeCorrection().
main()
int main (int argc, char * argv[])
If not already running, creates a detached process that will run as a daemon. Accepts one command line arg: -v that causes the daemon to run in verbose mode which writes a status string and event messages to the console once per second. These messages continue until the console that started the pps-client daemon is closed.
Alternatively, if the daemon is already running, displays a statement to that effect and accepts the following optional command line args:
The -v flag starts the second-by-second display of a status string that will continue until ended by ctrl-c.
The -s flag requests that specified files be saved. If the -s flag is not followed by a file specifier, a list of the files that can be saved is printed.
Definition at line 1407 of file pps-client.cpp.
References accessDaemon(), bufferStatusMsg(), createPIDfile(), G::doNISTsettime, f, find_source(), g, getRootHome(), initialize(), sysCommand(), waitForPPS(), and writeToLog().
makeAverageIntegral()
void makeAverageIntegral (double avgCorrection)
Constructs, at each second over the last 10 seconds in each minute, 10 integrals of the average time correction over the last minute.
These integrals are then averaged to G.avgIntegral just before the minute rolls over. The use of this average of the last 10 integrals to correct the frequency offset of the system clock provides a modest improvement over using only the single last integral.
Parameters
[in] avgCorrection The average correction to be integrated.
Definition at line 295 of file pps-client.cpp.
References G::avgIntegral, G::correctionFifo_idx, g, HARD_LIMIT_1, G::hardLimit, G::integral, G::integralCount, NUM_INTEGRALS, PER_NUM_INTEGRALS, and SECS_PER_MINUTE.
Referenced by makeTimeCorrection().
makeTimeCorrection()
int makeTimeCorrection (struct timeval pps_t)
Makes time corrections each second, frequency corrections each minute and removes jitter from the PPS time reported by pps_t.
Jitter is removed by clamping corrections to a sequence of positive and negative values each of magnitude one microsec. Thus the average timeCorrection, which is forced to be zero by the controller, also corresponds to a time delay where the number of positive and negative corrections are equal. Thus the correction is the median of the time delays causing the corrections rather than the average value of those delays. This strategy almost completely eliminates second-by-second noise.
This function is called by readPPS_SetTime() from within the one-second delay loop in the waitForPPS() function.
Parameters
[in] pps_t The delayed time of the PPS rising edge returned by the system clock.
Returns
0 on success else -1 on system error.
Definition at line 976 of file pps-client.cpp.
References G::activeCount, adjtimex(), ADJTIMEX_SCALE, G::avgCorrection, doTimeFixups(), G::freqOffset, g, getAcquireState(), getIntegral(), getMovingAverage(), G::integralGain, integralIsReady(), G::integralTimeCorrection, G::interruptReceived, G::invProportionalGain, G::isControlling, G::isDelaySpike, makeAverageIntegral(), G::ppsTimestamp, G::rawError, recordOffsets(), removeNoise(), savePPStime(), G::seq_num, signedFractionalSeconds(), G::t3, G::t_count, G::t_now, G::timeCorrection, G::zeroError, and G::zeroOffset.
Referenced by readPPS_SetTime().
rawErr()
class List rawErr (SLEW_LEN)
Referenced by getTimeSlew().
readPPS_SetTime()
int readPPS_SetTime (bool verbose, timeCheckParams * tcp, pps_handle_t * pps_handle, int * pps_mode)
Requests a read of the timestamp of the PPS hardware interrupt by the system PPS driver and passes the value read to makeTimeCorrection().
The first time pps-client runs, the time slew can be as large as hundreds of milliseconds. When this is the case, limits imposed by adjtimex() prevent changes in offset of more than about 500 microseconds each second. As a result, pps-client will make a partial correction each minute and will restart several times before the slew is small enough that getAcquireState() will set G.isControlling to "true". This looping will eventually converge but can take as long as 20 minutes.
Parameters
[in] verbose If "true" then write pps-client state status messages to the console. Else not.
[in] tcp State data for makeNISTTimeQuery
[in] pps_handle The handle to the system PPS device.
[in] pps_mode The system PPS device mode.
Returns
0 if no restart is required, 1 if restart is required or -1 on system error.
Definition at line 1134 of file pps-client.cpp.
References G::avgSlew, bufferStatusMsg(), detectMissedPPS(), g, HARD_LIMIT_1024, G::hardLimit, initialize(), G::interruptLost, G::isControlling, makeTimeCorrection(), readPPSTimestamp(), SECS_PER_MINUTE, G::seq_num, SLEW_MAX, STRBUF_SZ, G::t, G::tm, and writeToLog().
Referenced by waitForPPS().
removeNoise()
int removeNoise (int rawError)
Removes delay spikes and jitter from rawError and returns the resulting clamped zeroError.
Parameters
[in] rawError The raw error value to be processed.
Returns
The resulting zeroError value.
Definition at line 601 of file pps-client.cpp.
References G::avgCorrection, buildErrorDistrib(), buildJitterDistrib(), buildRawErrorDistrib(), G::clampAbsolute, clampJitter(), detectDelaySpike(), g, getAvgNoiseLevel(), getTimeSlew(), INV_GAIN_1, G::invProportionalGain, G::isControlling, G::isDelaySpike, G::ppsCount, G::rawErrorDistrib, G::seq_num, setHardLimit(), SETTLE_TIME, writeErrorDistrib, and writeJitterDistrib.
Referenced by makeTimeCorrection().
savePPStime()
void savePPStime (int timeCorrection)
Gets the time of the PPS rising edge from the timeCorrection value and sets the corresponding timestamp.
Parameters
[in] timeCorrection The correction to be applied to get the time of the PPS rising edge.
Definition at line 674 of file pps-client.cpp.
References g, and writeTimestamp().
Referenced by makeTimeCorrection().
setClockFractionalSecond()
void setClockFractionalSecond (int correction)
Corrects the system time whenever the system clock is set externally.
The external device that sets the clock might inject a non-zero fractional second along with the whole seconds. It is assumed that the whole system clock seconds would have the same value as the whole PPS seconds. So the correction to the fractional second that is made must not cause a change to the whole seconds.
Because the adjtimex() function will not accept a negative number as a fractional second and the correction value is a positive number then to subtract the correction, (1e6 - correction) microseconds is added instead.
If correction is less than half a second then (1e6 - correction) is greater than half a second. That would push the system clock one second ahead of the PPS. To prevent that, one second is subtracted from the system clock whole seconds.
If the correction is greater than a half second then (1e6 - correction) is less than half a second so no change to the system clock whole seconds is necessary.
If the correction is near half a second, handling of the whole second is ambiguous and the change to the whole second could be wrong. In that case the the whole second error would eventually be caught by a time update from the external timekeeper and corrected then.
Parameters
[in] correction The fractional second correction value in microseconds.
Definition at line 830 of file pps-client.cpp.
References adjtimex(), g, G::t3, G::t_count, G::t_now, USECS_PER_SEC, and writeToLog().
Referenced by correctFractionalSecond().
setClockToGPStime()
void setClockToGPStime (void)
If GPS time through a serial port is enabled in pps-client.conf, sets the system time whenever there is an error relative to the whole seconds obtained through the serial port by writing the whole second correction to the adjtimex function.
Errors are infrequent. But if one occurs the whole seconds of system clock are set.
Definition at line 454 of file pps-client.cpp.
References adjtimex(), g, G::serialTimeError, G::serialTimeUpdated, G::t3, and writeToLog().
Referenced by doTimeFixups().
setClocktoNISTtime()
void setClocktoNISTtime (void)
If NIST time is enabled in pps-client.conf, sets the system time whenever there is an error relative to the whole seconds obtained from Internet NIST servers by writing the whole second correction to the adjtimex function.
Errors are infrequent. But if one occurs the whole seconds of system clock are set following the CHECK_TIME interval.
Definition at line 415 of file pps-client.cpp.
References adjtimex(), G::consensusTimeError, g, G::nistTimeUpdated, G::t3, and writeToLog().
Referenced by doTimeFixups().
setHardLimit()
void setHardLimit (double avgCorrection)
Uses G.avgSlew or avgCorrection and the curent hard limit, G.hardLimit, to determine the global G.hardLimit to set on zeroError to convert error values to time corrections.
Because it is much more effective and does not introduce additional time delay, hard limiting is used instead of filtering to remove noise (jitter) from the reported time of PPS capture.
Parameters
[in] avgCorrection Current average correction value.
Definition at line 162 of file pps-client.cpp.
References G::activeCount, G::avgSlew, g, HARD_LIMIT_NONE, G::hardLimit, SECS_PER_MINUTE, and SLEW_MAX.
Referenced by removeNoise().
setSyncDelay()
struct timespec setSyncDelay (int timeAt, int fracSec)
Sets a nanosleep() time delay equal to the time remaining in the second from the time recorded as fracSec plus an adjustment value of timeAt in microseconds.
Parameters
[in] timeAt The adjustment value in microseconds.
[in] fracSec The fractional second part of the system time in microseconds.
Returns
The length of time to sleep in seconds and nanoseconds.
Definition at line 1044 of file pps-client.cpp.
References g, INTERRUPT_LOST, G::interruptLossCount, G::interruptReceived, SECS_PER_HOUR, G::seq_num, and writeToLog().
Referenced by showStatusEachSecond(), and waitForPPS().
signedFractionalSeconds()
int signedFractionalSeconds (int fracSec)
Gets the fractional seconds part of interrupt time and if the value should be interpreted as negative then translates the value.
Parameters
[in] fracSec The delayed time of the PPS rising edge returned by the system clock.
Returns
The signed fractional seconds part of the time.
Definition at line 704 of file pps-client.cpp.
References USECS_PER_SEC.
Referenced by makeTimeCorrection().
waitForPPS()
void waitForPPS (bool verbose, pps_handle_t * pps_handle, int * pps_mode)
Runs the one-second wait loop that waits for the PPS hardware interrupt that returns the timestamp of the interrupt which is passed to makeTimeCorrection().
Parameters
[in] verbose If "true" then write pps-client state status messages to the console. Else not.
[in] pps_handle The handle to the system PPS device.
[in] pps_mode The the system PPS device mode.
Definition at line 1250 of file pps-client.cpp.
References allocInitializeNISTThreads(), allocInitializeSerialThread(), timeCheckParams::attr, bufferStateParams(), checkPPSInterrupt(), G::doNISTsettime, G::doSerialsettime, freeNISTThreads(), freeSerialThread(), g, getConfigs(), getNearestSecond(), HUPhandler(), G::interruptLost, G::isControlling, G::isDelaySpike, G::isVerbose, loadLastState(), makeNISTTimeQuery(), makeSerialTimeQuery(), PPS_WINDOW, readPPS_SetTime(), readState, saveGPSTime(), saveLastState(), setSyncDelay(), sysCommand(), G::t_count, G::t_now, TERMhandler(), threadIsRunning, timeCheckParams::tid, version, writeStatusStrings(), and writeToLog().
Referenced by main().
Variable Documentation
f
struct ppsFiles f
PPS-Client internal files.
PPS-Client internal files.
Definition at line 58 of file pps-files.cpp.
Referenced by main().
g
struct G g
Declares the global variables defined in pps-client.h.
Definition at line 53 of file pps-client.cpp.
Referenced by alignNumbersAfter(), alignTokens(), assignProcessorAffinity(), bufferStateParams(), bufferStatusMsg(), buildErrorDistrib(), buildJitterDistrib(), buildRawErrorDistrib(), clampJitter(), createPIDfile(), daemonSaveArray(), detectDelaySpike(), detectExteralSystemClockChange(), detectMissedPPS(), doTimeFixups(), find_source(), getAcquireState(), getChildPID(), getConfigs(), getIntegral(), getLinuxVersion(), getMovingAverage(), getRootHome(), getRPiCPU(), getSharedConfigs(), getString(), getTimeSlew(), hasString(), initialize(), integralIsReady(), INThandler(), loadLastState(), main(), makeAverageIntegral(), makeTimeCorrection(), open_logerr(), parseSaveDataRequest(), ppsIsRunning(), processWriteRequest(), read_logerr(), readPPS_SetTime(), recordFrequencyVars(), recordOffsets(), removeNoise(), saveDoubleArray(), saveLastState(), savePPStime(), setClockFractionalSecond(), setClockToGPStime(), setClocktoNISTtime(), setHardLimit(), setSyncDelay(), showStatusEachSecond(), sysCommand(), TERMhandler(), waitForPPS(), writeDistribution(), writeErrorDistribFile(), writeFileMsgToLog(), writeFrequencyVars(), writeJitterDistribFile(), writeOffsets(), writeStatusStrings(), writeTimestamp(), and writeToLog().
readState
bool readState = false
Definition at line 65 of file pps-client.cpp.
Referenced by waitForPPS().
threadIsRunning
bool threadIsRunning = false
Definition at line 64 of file pps-client.cpp.
Referenced by waitForPPS().
version
const char* version = "2.0.1"
Program v2.0.0 updated on 9 Jul 2020.
System call
Definition at line 53 of file pps-client.cpp.
Referenced by accessDaemon(), and waitForPPS().
writeErrorDistrib
bool writeErrorDistrib
Definition at line 58 of file pps-files.cpp.
Referenced by getConfigs(), and removeNoise().
writeJitterDistrib
bool writeJitterDistrib
Definition at line 57 of file pps-files.cpp.
Referenced by getConfigs(), and removeNoise().